name: Publish the website to another repo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: |
          npm i;
          npm run build;

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: 666pulse/solana-nft
          publish_branch: main  # default: gh-pages
          publish_dir: ./dist
          user_name: 'solana'
          user_email: 'solana.example@github.com'
